# Generated by Django 4.1.6 on 2023-02-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalRoom',
            fields=[
                ('room_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('room_capacity', models.IntegerField()),
                ('room_amenities', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(max_length=13)),
                ('date_admitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.doctor')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.hospitalroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('RRN', models.CharField(max_length=13)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.hospitalroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Free', 'Free'), ('Out of Service', 'Out of Service')], max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.hospitalroom')),
            ],
        ),
        migrations.AddField(
            model_name='hospitalroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.roomtype'),
        ),
    ]
